<a href="https://colab.research.google.com/github/eshwariegge/CSE-NASSCOM/blob/main/WEEK2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# -----------------------------------------------------------
# 🔹 1. ARRAY CREATION FUNCTIONS
# -----------------------------------------------------------
import numpy as np
# arange(): Create range of numbers like Python's range()
arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)



Array using arange: [0 2 4 6 8]


In [3]:
# linspace(): Create evenly spaced values between two limits
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)



Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [4]:
# reshape(): Change shape without changing data
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)

# flatten(): Convert multi-dimensional array to 1D
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]


In [5]:
# -----------------------------------------------------------
# 🔹 2. AGGREGATE FUNCTIONS
# -----------------------------------------------------------

data = np.array([[5, 8, 9], [2, 4, 6]])

print("Original Data:\n", data)


Original Data:
 [[5 8 9]
 [2 4 6]]


In [6]:
print("Sum of all elements:", np.sum(data))             # Total sum
print("Column-wise sum:", np.sum(data, axis=0))         # Sum along columns
print("Row-wise mean:", np.mean(data, axis=1))          # Average of each row
print("Max value:", np.max(data))                       # Maximum value



Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9


In [7]:
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))                       # Minimum value
print("Standard Deviation:", np.std(data))              # Spread of values



Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585
